### list all users with email
GET http://localhost:3000/auth/?email=jamashah@gmail.com

### fetch user with given id
GET http://localhost:3000/auth/2

### create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "Sameedkhan@gmail.com",
    "password": "123456"
}

### sign in user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "Sameedkhans@gmail.com",
    "password": "123456"
}

### update user with specific id
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "jamashah@gmail.com"
}

### delete a user with given ID
DELETE http://localhost:3000/auth/1